# Dependabot configuration for DevContainer Images
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
---
version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ironwolphern"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  # Docker dependencies - Ansible
  - package-ecosystem: "docker"
    directory: "/images/ansible"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    open-pull-requests-limit: 3
    reviewers:
      - "ironwolphern"
    labels:
      - "dependencies"
      - "docker"
      - "ansible"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  # Docker dependencies - Python
  - package-ecosystem: "docker"
    directory: "/images/python"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:15"
    open-pull-requests-limit: 3
    reviewers:
      - "ironwolphern"
    labels:
      - "dependencies"
      - "docker"
      - "python"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  # Docker dependencies - Terraform
  - package-ecosystem: "docker"
    directory: "/images/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:30"
    open-pull-requests-limit: 3
    reviewers:
      - "ironwolphern"
    labels:
      - "dependencies"
      - "docker"
      - "terraform"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  # Docker dependencies - Go
  - package-ecosystem: "docker"
    directory: "/images/go"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:45"
    open-pull-requests-limit: 3
    reviewers:
      - "ironwolphern"
    labels:
      - "dependencies"
      - "docker"
      - "go"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  # DevContainer dependencies
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 2
    reviewers:
      - "ironwolphern"
    labels:
      - "dependencies"
      - "devcontainer"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "ironwolphern"
  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "ironwolphern"
