name: 🐛 Bug Report
description: Report a bug or issue with the DevContainer images
title: "[BUG] "
labels: ["bug", "triage"]
assignees:
  - ironwolphern
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! This helps us improve the DevContainer images for everyone.

        Please fill out the information below to help us understand and reproduce the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: What you expected to happen
      placeholder: A clear description of what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened instead
      placeholder: A clear description of what actually happened...
    validations:
      required: true

  - type: dropdown
    id: image-type
    attributes:
      label: 🐳 DevContainer Image
      description: Which DevContainer image is affected?
      options:
        - Ansible
        - Python
        - Terraform
        - Go
        - Multiple images
      default: 0
    validations:
      required: true

  - type: input
    id: image-version
    attributes:
      label: 🏷️ Image Version/Tag
      description: What version or tag of the image are you using?
      placeholder: e.g., latest, v1.0.0, main
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 🖥️ Platform
      description: What platform are you running on?
      options:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
        - Other (please specify in additional context)
      default: 0
    validations:
      required: true

  - type: dropdown
    id: host-os
    attributes:
      label: 💻 Host Operating System
      description: What operating system is the host running?
      options:
        - macOS
        - Windows
        - Linux (Ubuntu)
        - Linux (Debian)
        - Linux (Fedora)
        - Linux (Other)
        - Other
      default: 0
    validations:
      required: true

  - type: input
    id: vscode-version
    attributes:
      label: 📝 VS Code Version
      description: What version of VS Code are you using?
      placeholder: e.g., 1.85.0
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: 📋 Relevant Log Output
      description: Please copy and paste any relevant log output
      render: shell
      placeholder: Paste any error messages, stack traces, or relevant logs here...

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Any other context about the problem
      placeholder: |
        - Configuration files (devcontainer.json, etc.)
        - Screenshots or recordings
        - Related issues
        - Workarounds you've tried

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have provided all the requested information above
          required: true
        - label: I can reproduce this issue consistently
          required: true
