name: 'Test Permissions'

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  issues: write
  pull-requests: write

jobs:
  test-api-access:
    name: 'Test GitHub API Access'
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Test API permissions'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              // Test reading repository information
              const repo = await github.rest.repos.get({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              console.log('✅ Repository API access: OK');
              
              // Test reading workflow runs (requires actions: read)
              const runs = await github.rest.actions.listWorkflowRunsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 1
              });
              console.log('✅ Workflow runs API access: OK');
              
              // Test current workflow run access
              const currentRun = await github.rest.actions.getWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.runId
              });
              console.log('✅ Current workflow run API access: OK');
              
              console.log('🎉 All API access tests passed!');
              
            } catch (error) {
              console.error('❌ API access error:', error.message);
              console.error('Error details:', error);
              throw error;
            }

      - name: 'Create test issue (will be closed immediately)'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              // Create a test issue
              const issue = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: '🧪 API Permissions Test',
                body: `This is a test issue to verify GitHub API permissions.
                
                **Created by**: ${{ github.workflow }}
                **Run ID**: ${{ github.run_id }}
                **Date**: ${new Date().toISOString()}
                
                This issue will be closed automatically.`,
                labels: ['test', 'automation']
              });
              
              console.log('✅ Issue created successfully:', issue.data.number);
              
              // Close the test issue immediately
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.data.number,
                state: 'closed'
              });
              
              console.log('✅ Test issue closed successfully');
              
            } catch (error) {
              console.error('❌ Issue creation error:', error.message);
              throw error;
            }
